name: mi_card_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
  
  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/pacifico/Pacifico-Regular.ttf
  - family: SourcePro
    fonts:
      - asset: fonts/sans_pro/SourceCodePro-Regular.ttf
      - asset: fonts/sans_pro/SourceCodePro-Bold.ttf
